# Generated by Django 5.0.2 on 2025-07-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solana_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solanauser',
            name='wallet_address',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
