# Generated by Django 5.0.2 on 2025-10-11 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solana_auth', '0002_make_wallet_address_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False, help_text='얼굴 인증 성공 여부')),
                ('confidence', models.DecimalField(decimal_places=4, help_text='인증 신뢰도 (0.0 ~ 1.0)', max_digits=5)),
                ('liveness_score', models.DecimalField(decimal_places=4, help_text='생체 확인 점수 (0.0 ~ 1.0)', max_digits=5)),
                ('attempts', models.IntegerField(default=1, help_text='인증 시도 횟수')),
                ('check_details', models.JSONField(blank=True, help_text='단계별 인증 상세 정보 (눈 깜박임, 고개 돌림 등)', null=True)),
                ('verification_timestamp', models.DateTimeField(help_text='프론트엔드에서 전송한 인증 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'face_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='face_verifi_user_id_d95bf7_idx'), models.Index(fields=['verified', '-created_at'], name='face_verifi_verifie_9737b6_idx')],
            },
        ),
    ]
