# Generated by Django 5.0.2 on 2025-10-12 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solana_auth', '0004_admingrade_adminpermission_adminuser_gradepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(help_text='팀원 사진 URL (S3)', max_length=500)),
                ('position_ko', models.CharField(help_text='직책 (한글) 예: GLI CEO', max_length=100)),
                ('position_en', models.CharField(help_text='직책 (영문) 예: Chief Executive Officer', max_length=100)),
                ('role_ko', models.TextField(help_text='역할 설명 (한글) 예: 블록체인 비즈니스 전략 및 전반적인 경영을 담당합니다.')),
                ('role_en', models.TextField(help_text='역할 설명 (영문) 예: Responsible for blockchain business strategy and overall management.')),
                ('tags', models.JSONField(default=list, help_text='기술 태그 배열 예: ["Blockchain", "Business Strategy", "Leadership"]')),
                ('order', models.IntegerField(default=0, help_text='표시 순서 (낮을수록 먼저 표시)')),
                ('is_active', models.BooleanField(default=True, help_text='팀원 표시 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'team_members',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['order', 'is_active'], name='team_member_order_a5326a_idx')],
            },
        ),
    ]
