# Generated by Django 5.0.2 on 2025-10-12 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solana_auth', '0005_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icon', models.CharField(help_text='아이콘 emoji 예: 🌊', max_length=10)),
                ('title_ko', models.CharField(help_text='제목 (한글) 예: 비전', max_length=200)),
                ('title_en', models.CharField(help_text='제목 (영문) 예: Vision', max_length=200)),
                ('description_ko', models.TextField(help_text='설명 (한글)')),
                ('description_en', models.TextField(help_text='설명 (영문)')),
                ('order', models.IntegerField(default=0, help_text='표시 순서 (낮을수록 먼저 표시)')),
                ('is_active', models.BooleanField(default=True, help_text='특징 표시 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_features',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['order', 'is_active'], name='project_fea_order_fc4473_idx')],
            },
        ),
    ]
