# Generated by Django 5.0.2 on 2025-10-12 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solana_auth', '0006_projectfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icon', models.CharField(help_text='아이콘 emoji 예: 🚀', max_length=10)),
                ('title_ko', models.CharField(help_text='제목 (한글) 예: 플랫폼 구축', max_length=200)),
                ('title_en', models.CharField(help_text='제목 (영문) 예: Platform Development', max_length=200)),
                ('description_ko', models.TextField(help_text='설명 (한글)')),
                ('description_en', models.TextField(help_text='설명 (영문)')),
                ('features', models.JSONField(default=list, help_text='주요 기능 목록 JSON 배열 예: ["웹 플랫폼 개발", "GLIB/GLID/GLIL 토큰 발행", "지갑 연동 시스템"]')),
                ('order', models.IntegerField(default=0, help_text='표시 순서 (낮을수록 먼저 표시)')),
                ('is_active', models.BooleanField(default=True, help_text='페이즈 표시 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'strategy_phases',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['order', 'is_active'], name='strategy_ph_order_bc8c62_idx')],
            },
        ),
    ]
