# Generated by Django 5.2.7 on 2025-10-12 16:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solana_auth', '0007_strategyphase'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quarter', models.CharField(help_text='분기 정보 예: 2024 Q1', max_length=20)),
                ('status_icon', models.CharField(help_text='상태 아이콘 예: ✅ (완료), 🔄 (진행중), ⏳ (대기)', max_length=10)),
                ('title_ko', models.CharField(help_text='제목 (한글) 예: 플랫폼 MVP 출시', max_length=200)),
                ('title_en', models.CharField(help_text='제목 (영문) 예: Platform MVP Launch', max_length=200)),
                ('description_ko', models.TextField(help_text='설명 (한글)')),
                ('description_en', models.TextField(help_text='설명 (영문)')),
                ('order', models.IntegerField(default=0, help_text='표시 순서 (낮을수록 먼저 표시)')),
                ('is_active', models.BooleanField(default=True, help_text='일정 표시 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'development_timelines',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['order', 'is_active'], name='development_order_7b87e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenEcosystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icon', models.CharField(help_text='아이콘 emoji 예: 🔵', max_length=10)),
                ('name', models.CharField(help_text='토큰 이름 예: GLI Business', max_length=100)),
                ('symbol', models.CharField(help_text='토큰 심볼 예: GLIB', max_length=20)),
                ('description_ko', models.TextField(help_text='설명 (한글)')),
                ('description_en', models.TextField(help_text='설명 (영문)')),
                ('features', models.JSONField(default=list, help_text='주요 기능 목록 JSON 배열')),
                ('total_supply', models.CharField(help_text='총 공급량 예: 100,000,000 GLIB 또는 무제한', max_length=100)),
                ('current_price', models.CharField(help_text='현재 가격 예: $0.25', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='표시 순서 (낮을수록 먼저 표시)')),
                ('is_active', models.BooleanField(default=True, help_text='토큰 표시 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'token_ecosystems',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['order', 'is_active'], name='token_ecosy_order_643813_idx')],
            },
        ),
    ]
