# Generated by Django 5.2.7 on 2025-10-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solana_auth', '0008_developmenttimeline_tokenecosystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='solanauser',
            name='vpx_experience',
            field=models.IntegerField(default=0, help_text='X(eXperience) 포인트: 1=웹3월렛연동, 2=GLIL사용, 4=GLIB사용 (비트플래그, 최대 7)'),
        ),
        migrations.AddField(
            model_name='solanauser',
            name='vpx_partner',
            field=models.IntegerField(default=0, help_text='P(Partner) 포인트: 1=GLID확보, 2=GLID예치, 4=GLIB엔젤&프리세일 (비트플래그, 최대 7)'),
        ),
        migrations.AddField(
            model_name='solanauser',
            name='vpx_verify',
            field=models.IntegerField(default=1, help_text='V(Verify) 포인트: 1=이메일인증, 2=핸드폰인증, 4=3D얼굴인증 (비트플래그, 최대 7)'),
        ),
    ]
