# Generated by Django 5.0.2 on 2025-10-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solana_auth', '0009_solanauser_vpx_experience_solanauser_vpx_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image_url',
            field=models.URLField(blank=True, help_text='팀원 사진 URL (S3) - 선택사항', max_length=500, null=True),
        ),
    ]
