# Generated by Django 5.0.2 on 2025-10-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solana_auth', '0010_make_image_url_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(default='Not Entered', help_text='이름 (영문) 예: GLI Kim', max_length=50),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ko',
            field=models.CharField(default='미입력', help_text='이름 (한글) 예: 김GLI', max_length=50),
        ),
    ]
