# Generated by Django 5.0.2 on 2025-10-20 13:38

from django.db import migrations, models


def migrate_features_data(apps, schema_editor):
    """기존 features 데이터를 features_ko로 복사"""
    StrategyPhase = apps.get_model('solana_auth', 'StrategyPhase')
    for phase in StrategyPhase.objects.all():
        # 기존 features 데이터를 features_ko로 복사
        phase.features_ko = phase.features if phase.features else []
        # features_en은 빈 배열로 초기화
        phase.features_en = []
        phase.save()


class Migration(migrations.Migration):

    dependencies = [
        ('solana_auth', '0011_add_name_fields_to_team_member'),
    ]

    operations = [
        # 1. 새 필드 추가 (nullable=True로 먼저 추가)
        migrations.AddField(
            model_name='strategyphase',
            name='features_ko',
            field=models.JSONField(default=list, help_text='주요 기능 목록 (한글) JSON 배열 예: ["웹 플랫폼 개발", "GLIB/GLID/GLIL 토큰 발행", "지갑 연동 시스템"]', null=True),
        ),
        migrations.AddField(
            model_name='strategyphase',
            name='features_en',
            field=models.JSONField(default=list, help_text='주요 기능 목록 (영문) JSON 배열 예: ["Web platform development", "GLIB/GLID/GLIL token issuance", "Wallet integration system"]', null=True),
        ),
        # 2. 데이터 마이그레이션
        migrations.RunPython(migrate_features_data, reverse_code=migrations.RunPython.noop),
        # 3. 기존 features 필드 삭제
        migrations.RemoveField(
            model_name='strategyphase',
            name='features',
        ),
        # 4. nullable=False로 변경
        migrations.AlterField(
            model_name='strategyphase',
            name='features_ko',
            field=models.JSONField(default=list, help_text='주요 기능 목록 (한글) JSON 배열 예: ["웹 플랫폼 개발", "GLIB/GLID/GLIL 토큰 발행", "지갑 연동 시스템"]'),
        ),
        migrations.AlterField(
            model_name='strategyphase',
            name='features_en',
            field=models.JSONField(default=list, help_text='주요 기능 목록 (영문) JSON 배열 예: ["Web platform development", "GLIB/GLID/GLIL token issuance", "Wallet integration system"]'),
        ),
    ]
