# Generated by Django 5.2.7 on 2025-10-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solana_auth', '0012_split_strategy_phase_features_to_ko_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenecosystem',
            name='features',
        ),
        migrations.AddField(
            model_name='tokenecosystem',
            name='features_en',
            field=models.JSONField(default=list, help_text='주요 기능 목록 (영문) JSON 배열 예: ["Participation in voting and decision-making", "Special benefits and rewards", "Platform growth revenue sharing"]'),
        ),
        migrations.AddField(
            model_name='tokenecosystem',
            name='features_ko',
            field=models.JSONField(default=list, help_text='주요 기능 목록 (한글) JSON 배열 예: ["투표 및 의사 결정 참여", "특별 혜택 및 보상", "플랫폼 성장 수익 공유"]'),
        ),
    ]
