# Generated by Django 5.0.2 on 2025-10-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solana_auth', '0013_remove_tokenecosystem_features_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authnonce',
            old_name='used',
            new_name='is_consumed',
        ),
    ]
