# Generated by Django 5.2.7 on 2025-10-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solana_auth', '0014_rename_used_to_is_consumed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmenttimeline',
            name='status_icon',
            field=models.URLField(blank=True, help_text='상태 아이콘 이미지 URL 예: https://example.com/status-icon.png', null=True),
        ),
        migrations.AlterField(
            model_name='projectfeature',
            name='icon',
            field=models.URLField(blank=True, help_text='아이콘 이미지 URL 예: https://example.com/icon.png', null=True),
        ),
        migrations.AlterField(
            model_name='strategyphase',
            name='icon',
            field=models.URLField(blank=True, help_text='아이콘 이미지 URL 예: https://example.com/icon.png', null=True),
        ),
        migrations.AlterField(
            model_name='tokenecosystem',
            name='icon',
            field=models.URLField(blank=True, help_text='아이콘 이미지 URL 예: https://example.com/icon.png', null=True),
        ),
    ]
