# Generated by Django 5.2.7 on 2025-10-30 19:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solana_auth', '0015_alter_developmenttimeline_status_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_ko', models.CharField(help_text='뉴스 제목 (한글)', max_length=200)),
                ('title_en', models.CharField(help_text='뉴스 제목 (영문)', max_length=200)),
                ('content_ko', models.TextField(help_text='뉴스 내용 (한글)')),
                ('content_en', models.TextField(help_text='뉴스 내용 (영문)')),
                ('image_url', models.URLField(blank=True, help_text='기사 대표 이미지 URL 예: https://example.com/news-image.jpg', null=True)),
                ('external_url', models.URLField(blank=True, help_text='기사 원문 링크 URL 예: https://news.example.com/article/12345', null=True)),
                ('publication_date', models.DateField(help_text='기사가 보도된 날짜')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('published', '발행됨'), ('archived', '보관됨')], default='draft', help_text='기사 상태 (draft: 임시저장, published: 발행됨, archived: 보관됨)', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='표시 순서 (낮을수록 먼저 표시)')),
                ('is_active', models.BooleanField(default=True, help_text='뉴스 표시 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news_articles',
                'ordering': ['-publication_date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'is_active'], name='news_articl_status_e91cb8_idx'), models.Index(fields=['publication_date', '-created_at'], name='news_articl_publica_cf7281_idx'), models.Index(fields=['order', 'is_active'], name='news_articl_order_a9d2f4_idx')],
            },
        ),
    ]
