# Generated by Django 5.2.7 on 2025-10-30 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solana_auth', '0016_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='인증할 이메일 주소', max_length=254)),
                ('code', models.CharField(help_text='6자리 인증 코드', max_length=6)),
                ('expires_at', models.DateTimeField(help_text='인증 코드 만료 시간')),
                ('is_used', models.BooleanField(default=False, help_text='인증 코드 사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_verification_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'code'], name='email_verif_email_f1cfa0_idx'), models.Index(fields=['email', 'is_used'], name='email_verif_email_287deb_idx'), models.Index(fields=['expires_at'], name='email_verif_expires_42d424_idx')],
            },
        ),
    ]
