# Generated by Django 5.2.7 on 2025-10-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gli_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwaasset',
            name='area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='면적(㎡)'),
        ),
        migrations.AddField(
            model_name='rwaasset',
            name='asset_location_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='자산 위치(영문)'),
        ),
        migrations.AddField(
            model_name='rwaasset',
            name='asset_type_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rwaasset',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rwaasset',
            name='name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rwaasset',
            name='operation_type',
            field=models.CharField(choices=[('rental', '임대'), ('consignment', '위탁 운영'), ('direct', '직접 운영'), ('development', '개발'), ('other', '기타')], default='rental', max_length=20, verbose_name='운영 형태'),
        ),
        migrations.AddField(
            model_name='rwaasset',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='rwaasset',
            name='asset_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='자산 위치'),
        ),
    ]
