# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gli_content', '0002_rwaasset_area_sqm_rwaasset_asset_location_en_and_more'),
    ]

    operations = [
        # 직접 SQL로 컬럼 이름 변경
        migrations.RunSQL(
            # Forward: gleb -> glib
            sql=[
                'ALTER TABLE rwa_assets RENAME COLUMN min_investment_gleb TO min_investment_glib;',
                'ALTER TABLE rwa_assets RENAME COLUMN max_investment_gleb TO max_investment_glib;',
                'ALTER TABLE rwa_assets RENAME COLUMN total_invested_gleb TO total_invested_glib;',
                'ALTER TABLE rwa_assets RENAME COLUMN funding_target_gleb TO funding_target_glib;',
            ],
            # Reverse: glib -> gleb (rollback용)
            reverse_sql=[
                'ALTER TABLE rwa_assets RENAME COLUMN min_investment_glib TO min_investment_gleb;',
                'ALTER TABLE rwa_assets RENAME COLUMN max_investment_glib TO max_investment_gleb;',
                'ALTER TABLE rwa_assets RENAME COLUMN total_invested_glib TO total_invested_gleb;',
                'ALTER TABLE rwa_assets RENAME COLUMN funding_target_glib TO funding_target_gleb;',
            ],
        ),
    ]
