# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gli_content', '0002_rwaasset_area_sqm_rwaasset_asset_location_en_and_more'),
    ]

    operations = [
        # 0001에서 이미 _glib으로 생성되므로 이 마이그레이션은 no-op
        # 기존 데이터베이스와의 호환성을 위해 유지하되 실제 작업은 수행하지 않음
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
