# Generated by Django 5.2.7 on 2025-10-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gli_content', '0003_rename_gleb_to_glib'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcategory',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='설명(영문)'),
        ),
        migrations.AddField(
            model_name='shoppingcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='카테고리명(영문)'),
        ),
        migrations.AddField(
            model_name='shoppingproduct',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='설명(영문)'),
        ),
        migrations.AddField(
            model_name='shoppingproduct',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='상품명(영문)'),
        ),
        migrations.AddField(
            model_name='shoppingproduct',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='간단한 설명(영문)'),
        ),
    ]
