# Generated by Django 5.2.7 on 2025-10-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gli_content', '0004_shoppingcategory_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rwaasset',
            options={'ordering': ['order', '-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='rwaasset',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
