# Generated by Django 5.2.7 on 2025-10-30 19:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gli_content', '0005_alter_rwaasset_options_rwaasset_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RWAAssetImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(verbose_name='이미지 URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='표시 순서')),
                ('is_primary', models.BooleanField(default=False, verbose_name='메인 이미지 여부')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='이미지 설명')),
                ('alt_text_en', models.CharField(blank=True, max_length=200, verbose_name='이미지 설명(영문)')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gli_content.rwaasset')),
            ],
            options={
                'db_table': 'rwa_asset_images',
                'ordering': ['order', '-is_primary', 'created_at'],
                'indexes': [models.Index(fields=['asset', 'is_primary'], name='rwa_asset_i_asset_i_6005dd_idx'), models.Index(fields=['asset', 'order'], name='rwa_asset_i_asset_i_a25586_idx')],
                'constraints': [models.CheckConstraint(check=models.Q(('order__gte', 0)), name='positive_order')],
            },
        ),
    ]
